name: Test Orca IaC action

on:
  - pull_request
  - push

jobs:
  iac_scan_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan IaC
        uses: ./
        with:
          api_token:
            ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key:
            "iwillsurvive"
          path:
            "test"
          format:
            "json"
          output:
            "results/"
          console_output: "cli"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: orca-results
          path: results/
